repos:
  - repo: https://github.com/pycqa/isort
    rev: '5.13.0'
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: '24.2.0'
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.2'
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: 'v3.1.0'
    hooks:
    - id: add-trailing-comma
      args: [--py36-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
