version: "3.9"

name: tusdatos

services:
  tusdatos:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: tusdatos
    container_name: tusdatos
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    command: [ "/start" ]

  tusdatos-mongo-db:
    image: mongo:7.0
    container_name: tusdatos-mongo-db
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - tusdatos-mongo-db-data:/data/db

  tusdatos-postgres-db:
    image: postgres:16
    container_name: tusdatos-postgres-db
    volumes:
      - tusdatos-postgres-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  tusdatos-mongo-db-data:
  tusdatos-postgres-db-data:
